---
title: "Battillaria attramentaria"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Miura et al 2006 PNAS
### Using Japan (native) vs wNA
### nloci = 1 mtDNA sequences
### nind = 180 ind 

```{r echo = F}
rm(list=ls())
#library(readxl)
library(spatstat,warn.conflicts = F,quietly = T) # marks, ppp, quadratcount
library(scales,warn.conflicts = F,quietly = T) # alpha

domain <- c(-130,180,-50,75) 
load("../../output/df.globe.Rda")
meta <- read.csv("Battr_180inds_meta.csv")
# make unique pop matrix
tmp <- data.frame(Longitude = tapply(meta$lonInd,meta$popID,mean),
Latitude=tapply(meta$latInd,meta$popID,mean))
tmp$country <- meta$country[match(rownames(tmp),meta$popID)]
#reg.to.use <- matrix(c(
#"China Japan","Native",
#"France","Eur",
#"Korea","Native",
#"Mexico","wNA",
#"USA","wNA"),ncol=2,byrow = T)
#tmp$region <- reg.to.use[match(tmp$country,reg.to.use[,1]),2]
## find which quadrat each pop
gridIDs.tmp <- c()
for (i in 1:length(rownames(tmp)))
{
  ppp.tmp <- ppp(x=tmp$Longitude[rownames(tmp)==rownames(tmp)[i]],y=tmp$Latitude[rownames(tmp)==rownames(tmp)[i]],xrange=domain[1:2],yrange=domain[3:4])
  grid.tmp <- quadratcount(ppp.tmp, nx = abs(domain[1]-domain[2]), ny = abs(domain[3]-domain[4]))
  df.tmp <- data.frame(grid.tmp,quadIDs=1:dim(df.globe)[1])
  gridIDs.tmp <- c(gridIDs.tmp,df.tmp$quadIDs[df.tmp$Freq==1])
}
gridIDs.meta <- data.frame(gridIDs=gridIDs.tmp,pop=rownames(tmp))
gridIDs.meta$vars <- df.globe[match(gridIDs.meta$gridIDs,df.globe$gridID),]

plot(df.globe$plotted.Var1,df.globe$plotted.Var2,pch=21,col=alpha(c("black","red","blue")[factor(df.globe$reg)],.4),yaxt="n",xaxt="n",ylab="",xlab="",main="Asia (black); wNA (red); Europe (blue) " )

points(gridIDs.meta$vars$plotted.Var1,gridIDs.meta$vars$plotted.Var2,pch=20,cex=2,col=alpha(c("black","red","blue")[as.factor(gridIDs.meta$vars$reg)],.4))
write.csv(gridIDs.meta,"battr_meta.csv",quote=F,row.names = F)
```

## combine pops in that are within the same 1x1ยบ block
### Phist

```{r echo = F}
library(strataG,warn.conflicts = F,quietly = T)
library(ape,warn.conflicts = F,quietly = T)
dat <- read.dna("Battr_180inds.fas",format="fasta")
meta$gridIDs <- gridIDs.meta$gridIDs[match(meta$popID,gridIDs.meta$pop)]
## pull out grids with only 1 individual 
toKeep <- names(table(meta$gridIDs))[table(meta$gridIDs)>1]
strata <- meta$gridIDs
names(strata) <- meta$indID
gi <- sequence2gtypes(dat,strata)
gi <- gi[,,toKeep] 
fst <- pairwiseTest(gi,nrep = 1,by.locus = F,quietly=T) 

fst2 <- pairwiseSummary(fst)
colnames(fst2)[colnames(fst2)=="strata.1"] <- "gridID.1"
colnames(fst2)[colnames(fst2)=="strata.2"] <- "gridID.2"
save(fst2,file = "battr_mtdna_Fst.Rda")
print(head(fst2))

fst2$PHIst_noNegs <- ifelse(fst2$PHIst<0,0,fst2$PHIst) # get rid of negatives
fst.threshold <- ifelse(fst2$PHIst_noNegs==0,fst2$PHIst_noNegs,NA) # threshold

fst2$ax <- gridIDs.meta$vars$plotted.Var1[match(fst2$gridID.1,gridIDs.meta$gridIDs)]
fst2$ay <- gridIDs.meta$vars$plotted.Var2[match(fst2$gridID.1,gridIDs.meta$gridIDs)]
fst2$bx <- gridIDs.meta$vars$plotted.Var1[match(fst2$gridID.2,gridIDs.meta$gridIDs)]
fst2$by <- gridIDs.meta$vars$plotted.Var2[match(fst2$gridID.2,gridIDs.meta$gridIDs)]

plot(df.globe$plotted.Var1,df.globe$plotted.Var2,pch=21,col=alpha(c("black","red","blue")[factor(df.globe$reg)],.4),yaxt="n",xaxt="n",ylab="",xlab="",main="Asia (black); wNA (red); Europe (blue) " )

points(gridIDs.meta$vars$plotted.Var1,gridIDs.meta$vars$plotted.Var2,pch=20,cex=2,col=alpha(c("black","red","blue")[as.factor(gridIDs.meta$vars$reg)],.4))
mtext("fst=0",side=3,line=-1)
### only plot segments with Fst < 0.1
segments(fst2$ax,fst2$ay,fst2$bx,fst2$by,col=alpha("black",.5),lwd=fst.threshold+1)

#make a map with these same lines

fst2$gridID.1.lon <- df.globe$lon[match(fst2$gridID.1,df.globe$gridID)]
fst2$gridID.1.lat <- df.globe$lat[match(fst2$gridID.1,df.globe$gridID)]
fst2$gridID.2.lon <- df.globe$lon[match(fst2$gridID.2,df.globe$gridID)]
fst2$gridID.2.lat <- df.globe$lat[match(fst2$gridID.2,df.globe$gridID)]
fst2$reg.1 <- df.globe$reg[match(fst2$gridID.1,df.globe$gridID)]
fst2$reg.2 <- df.globe$reg[match(fst2$gridID.1,df.globe$gridID)]

plot(df.globe[df.globe$coastline==1,c(2,1)],cex=.1,xlim=c(-130,145),ylim=c(30,60),pch=19)
points(df.globe[df.globe$grid.for.model==1,c(2,1)],col="red",pch=20,cex=0.5)
segments(fst2$gridID.1.lon,fst2$gridID.1.lat,fst2$gridID.2.lon,fst2$gridID.2.lat,col="black",lwd=fst.threshold+1)

```
\newpage

### overall Fst

```{r echo = F}
overallFst <- overallTest(gi,nrep=1,quietly=T)$result
save(overallFst,file = "battr_mtdna_FstOverall.Rda")
print(overallFst)

```


### 3 region Fst

```{r echo = F}
reg <- gridIDs.meta$vars$reg[match(getStrata(gi),gridIDs.meta$gridIDs)]
gi2 <- gi
names(reg) <- names(getStrata(gi))
setStrata(gi2) <- reg
fst <- pairwiseTest(gi2,nrep = 1,by.locus = F,quietly=T) 
fst2 <- pairwiseSummary(fst)
colnames(fst2)[colnames(fst2)=="strata.1"] <- "gridID.1"
colnames(fst2)[colnames(fst2)=="strata.2"] <- "gridID.2"
save(fst2,file = "battr_mtdna_FstNatNon.Rda")
print(fst2)
```

### native vs non-native Fst

```{r echo = F}
#reg <- gridIDs.meta$vars$reg[match(dat$Pop,gridIDs.meta$gridIDs)]
reg2 <- ifelse(reg=="1_Asia","native","nonnative")
names(reg2) <- names(getStrata(gi))
gi3 <- gi
setStrata(gi3) <- reg2
fst <- pairwiseTest(gi3,nrep = 1,by.locus = F,quietly=T) 
fst2 <- pairwiseSummary(fst)
colnames(fst2)[colnames(fst2)=="strata.1"] <- "gridID.1"
colnames(fst2)[colnames(fst2)=="strata.2"] <- "gridID.2"
save(fst2,file = "battr_mtdna_Fst3region.Rda")
print(fst2)
```

\newpage

### within pop nucleotide divergence (also saved between pop divergence)

```{r echo = F}
nd <- nucleotideDivergence(gi)
#hexp <- aggregate(out$exptd.het,by=list(out$stratum),mean)
#colnames(hexp) <- c("gridID","Hexp")
print(nd$within)
save(nd,file = "battr_mtdna_nd.Rda")

plot(df.globe$plotted.Var1,df.globe$plotted.Var2,pch=21,col=alpha(c("black","red","blue")[factor(df.globe$reg)],.4),yaxt="n",xaxt="n",ylab="",xlab="",main="Asia (black); wNA (red); Europe (blue) " )
points(gridIDs.meta$vars$plotted.Var1,gridIDs.meta$vars$plotted.Var2,pch=20,cex=2,col=alpha(c("black","red","blue")[as.factor(gridIDs.meta$vars$reg)],.4))

nd.to.plot <- nd$within$mean[match(gridIDs.meta$vars$gridID,nd$within$stratum)]
points(gridIDs.meta$vars$plotted.Var1,gridIDs.meta$vars$plotted.Var2,pch=20,cex=2000*nd.to.plot,col=alpha(c("black","red","blue")[as.factor(gridIDs.meta$vars$reg)],.4))


```

