---
title: "Grid map"
output: pdf_document
fig_width: 6
fig_height: 5
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Native range - Identify sources

```{r echo = F}
rm(list=ls())
library(scales,warn.conflicts = F,quietly = T) # alpha
load("../output/df.globe.Rda")
library(maps,warn.conflicts = F,quietly = T)
library(mapdata,warn.conflicts = F,quietly = T)
library(sp,warn.conflicts=F,quietly=T)
library(maptools,warn.conflicts = F,quietly = T)
data(wrld_simpl)
plot(wrld_simpl, col = "grey", axes = T)
all <- df.globe[df.globe$grid.for.model==1,]
## make 1 x 1 deg squares 
all$lat.sq1 <- all$lat-.5
all$lat.sq2 <- all$lat+.5
all$lon.sq1 <- all$lon-.5
all$lon.sq2 <- all$lon+.5
points(all$lon, all$lat, pch=19, col="red", cex=.1)  

```
\newpage  

```{r echo = F}
## asia
hok <- all[all$lon<=145 & all$lon>=138&all$lat<=46&all$lat>=41,]
hon <- all[all$lon<=143 & all$lon>=140&all$lat<=40.5&all$lat>=36,]
hon <- hon[!hon$gridID%in%c(33785,33786),]
tok <- all[all$lon<=141 & all$lon>=136&all$lat<=36&all$lat>=33,]
tok <- tok[!tok$gridID%in%c(33290,33667),]
sea <- all[all$lon<=136 & all$lon>=131&all$lat<=35&all$lat>=32,]
sea <- sea[!sea$gridID%in%c(32666,32668),]
kag <- all[all$lon<=132 & all$lon>=128 & all$lat<=33.5 & all$lat>=30,]
kag <- kag[!kag$gridID==32667,]
source <- rbind(hok,hon,tok,sea,kag)
nonSource <- all[all$reg=="1_Asia" & !all$gridID%in%source$gridID,]
out <- rbind(source,nonSource)
out$sourceID <- factor(c(rep("hok",nrow(hok)),
                     rep("hon",nrow(hon)),
                     rep("tok",nrow(tok)),
                     rep("sea",nrow(sea)),
                     rep("kag",nrow(kag)),
                     rep("nonSource",nrow(nonSource))))
out$sourceID <- factor(out$sourceID,levels=levels(out$sourceID)[c(1,2,6,5,3,4)])
write.csv(out,"../output/df.globe_source.csv",quote=F,row.names = F)

map1 <- function() {
  map("worldHires",xlim=c(117.5,150),ylim=c(30,47),col="gainsboro",fill=TRUE)
  rect(all$lon.sq1,all$lat.sq2,all$lon.sq2,all$lat.sq1)
  box()
  rect(hok$lon.sq1,hok$lat.sq2,hok$lon.sq2,hok$lat.sq1,col=alpha("blue",.5))
  rect(hon$lon.sq1,hon$lat.sq2,hon$lon.sq2,hon$lat.sq1,col=alpha("darkgreen",.5))
  rect(tok$lon.sq1,tok$lat.sq2,tok$lon.sq2,tok$lat.sq1,col=alpha("black",.5))
  rect(sea$lon.sq1,sea$lat.sq2,sea$lon.sq2,sea$lat.sq1,col=alpha("red",.5))
  rect(kag$lon.sq1,kag$lat.sq2,kag$lon.sq2,kag$lat.sq1,col=alpha("lightgreen",.5))
  text(x=c(144.7672,143.0341,140.8678,134.6165,124.37), y=c(41.37038, 38.15945, 34.36471,32,31),c("Hokkaido","Miyagi","Tokyo","Seto Inland Sea","Kagoshima"),col=c("blue","darkgreen","black","red","lightgreen"),pos=4,cex=.7)
  points(x=nonSource$lon,y=nonSource$lat,pch=20)
  text(x=125,y=44,"nonSource",cex=.7);points(x=122.1,y=44,pch=20)
}
map1()

plot(df.globe$plotted.Var1,df.globe$plotted.Var2,pch=21,col=alpha(c("black","red","blue")[factor(df.globe$reg)],.4),yaxt="n",xaxt="n",ylab="",xlab="",main="Asia (black); wNA (red); Europe (blue)" )

points(x=out$plotted.Var1,y=out$plotted.Var2,col=c("blue","darkgreen","black","red","lightgreen")[out$sourceID],lwd=2,cex=2)
points(x=nonSource$plotted.Var1,y=nonSource$plotted.Var2,pch=20)

```

\newpage  

# Crassostrea gigas - SNPs

```{r echo = F}

gigas <- read.csv("../data/cgiga_snp/cgiga_meta.csv")
map1()
points(gigas$vars.lon,gigas$vars.lat,pch=20,cex=4)

plot(df.globe$plotted.Var1,df.globe$plotted.Var2,pch=21,col=alpha(c("black","red","blue")[factor(df.globe$reg)],.4),yaxt="n",xaxt="n",ylab="",xlab="",main="Asia (black); wNA (red); Europe (blue) " )

points(gigas$vars.plotted.Var1,gigas$vars.plotted.Var2,pch=20,cex=2,col=alpha(c("black","red","blue")[as.factor(gigas$vars.reg)],.4))

points(x=out$plotted.Var1,y=out$plotted.Var2,col=c("blue","darkgreen","black","red","lightgreen")[out$sourceID],lwd=2,cex=2)
points(x=nonSource$plotted.Var1,y=nonSource$plotted.Var2,pch=20)



```

# Gracilaria vermiculophylla - usat  

```{r echo = F}
gverm <- read.csv("../data/gverm_usat/gverm_meta.csv")
map1()
points(gverm$vars.lon,gverm$vars.lat,pch=20,cex=4)

plot(df.globe$plotted.Var1,df.globe$plotted.Var2,pch=21,col=alpha(c("black","red","blue")[factor(df.globe$reg)],.4),yaxt="n",xaxt="n",ylab="",xlab="",main="Asia (black); wNA (red); Europe (blue) " )
points(gverm$vars.plotted.Var1,gverm$vars.plotted.Var2,pch=20,cex=2,col=alpha(c("black","red","blue")[as.factor(gverm$vars.reg)],.4))
points(x=out$plotted.Var1,y=out$plotted.Var2,col=c("blue","darkgreen","black","red","lightgreen")[out$sourceID],lwd=2,cex=2)
points(x=nonSource$plotted.Var1,y=nonSource$plotted.Var2,pch=20)

```

# Batillaria attramentaria - mtDNA

```{r echo = F}
battr <- read.csv("../data/battr_mtdna/battr_meta.csv")
map1()
points(battr$vars.lon,battr$vars.lat,pch=20,cex=4)

plot(df.globe$plotted.Var1,df.globe$plotted.Var2,pch=21,col=alpha(c("black","red","blue")[factor(df.globe$reg)],.4),yaxt="n",xaxt="n",ylab="",xlab="",main="Asia (black); wNA (red); Europe (blue) " )
points(battr$vars.plotted.Var1,battr$vars.plotted.Var2,pch=20,cex=2,col=alpha(c("black","red","blue")[as.factor(battr$vars.reg)],.4))
points(x=out$plotted.Var1,y=out$plotted.Var2,col=c("blue","darkgreen","black","red","lightgreen")[out$sourceID],lwd=2,cex=2)
points(x=nonSource$plotted.Var1,y=nonSource$plotted.Var2,pch=20)

```

# Undaria pinnitifida - mtDNA  

```{r echo = F}
upinn <- read.csv("../data/upinn_mtdna/upinn_meta.csv")
map1()
points(upinn$vars.lon,upinn$vars.lat,pch=20,cex=4)

plot(df.globe$plotted.Var1,df.globe$plotted.Var2,pch=21,col=alpha(c("black","red","blue")[factor(df.globe$reg)],.4),yaxt="n",xaxt="n",ylab="",xlab="",main="Asia (black); wNA (red); Europe (blue) " )
points(upinn$vars.plotted.Var1,upinn$vars.plotted.Var2,pch=20,cex=2,col=alpha(c("black","red","blue")[as.factor(upinn$vars.reg)],.4))
points(x=out$plotted.Var1,y=out$plotted.Var2,col=c("blue","darkgreen","black","red","lightgreen")[out$sourceID],lwd=2,cex=2)
points(x=nonSource$plotted.Var1,y=nonSource$plotted.Var2,pch=20)

```

# Sargassum muticum - usat  

```{r echo = F}
smuti <- read.csv("../data/smuti_usat/smuti_meta.csv")
map1()
points(smuti$vars.lon,smuti$vars.lat,pch=20,cex=4)

plot(df.globe$plotted.Var1,df.globe$plotted.Var2,pch=21,col=alpha(c("black","red","blue")[factor(df.globe$reg)],.4),yaxt="n",xaxt="n",ylab="",xlab="",main="Asia (black); wNA (red); Europe (blue) " )
points(smuti$vars.plotted.Var1,smuti$vars.plotted.Var2,pch=20,cex=2,col=alpha(c("black","red","blue")[as.factor(smuti$vars.reg)],.4))
points(x=out$plotted.Var1,y=out$plotted.Var2,col=c("blue","darkgreen","black","red","lightgreen")[out$sourceID],lwd=2,cex=2)
points(x=nonSource$plotted.Var1,y=nonSource$plotted.Var2,pch=20)
```

